--- #YAML:1.0
name: haver-tk
version: 0.06
author:
  - Bryan Donlan <bdonlan@bd-home-comp.no-ip.org>
abstract: Perl extension for blah blah blah
license: gpl
requires:
  Data::Dumper: 2.121
  Haver: 0.06
  Haver::Client: 0.06
  POE: 0.27
  POE::Component::Client::Haver: 0.06
  Tk: 800
  perl: 5.6.1
recommends:
  Tk::HistEntry: 0.42
provides:
  Haver::Tk:
    file: lib/Haver/Tk.pm
    version: 0.06
generated_by: Module::Build version 0.24
